name: Lighthouse CI
on: pull_request
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            https://www.dylanamartin.com/
            https://www.dylanamartin.com/blog.html
            https://www.dylanamartin.com/projects.html
            https://www.dylanamartin.com/talks.html
            https://www.dylanamartin.com/media.html
          budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage